swagger: '2.0'
info:
  title: Advising Notes API
  description: Get advising notes about students.
  version: '0.0'
  license:
    name: GNU Affero General Public License Version 3
    url: http://www.gnu.org/licenses/agpl-3.0.en.html
externalDocs:
  description: GitHub Repository
  url: https://github.com/osu-mist/advising-notes-API
basePath: /v1
produces:
  - application/json
paths:
  /notes/{studentID}:
    get:
      tags:
        - notes
      description: "Get all advising notes for a student."
      operationId: getNotes
      parameters:
        - in: path
          name: studentID
          required: true
          description: "OSU ID of Student"
          type: string
        - $ref: '#/parameters/pretty'
      responses:
        "200":
          description: "Successful response"
          schema:
            $ref: '#/definitions/ResultObject'
        "404":
          description: "Resource not found"
          schema:
            $ref: "#/definitions/Error"
  /notes/{studentID}/{noteID}:
    get:
      tags:
        - notes
      description: "Get a specific note by ID."
      operationId: getNoteByID
      parameters:
        - in: path
          name: studentID
          required: true
          description: "OSU ID of student"
          type: string
        - in: path
          name: noteID
          required: true
          description: "ID of note for a student"
          type: string
        - $ref: '#/parameters/pretty'
      responses:
        "200":
          description: "Successful response"
          schema:
            $ref: '#/definitions/ResultObject'
        "404":
          description: "Resource not found"
          schema:
            $ref: "#/definitions/Error"

parameters:
  pretty:
    name: pretty
    in: query
    type: boolean
    required: false
    description: If true, JSON response will be pretty-printed

definitions:
  ResultObject:
    properties:
      data:
        type: array
        items:
          $ref: "#/definitions/ResourceObject"
      links:
        $ref: "#/definitions/Links"
  ResourceObject:
    properties:
      id:
        type: string
      type:
        description: "Resource type: note"
        type: string
      attributes:
        $ref: "#/definitions/Attributes"
      links:
        properties:
          self:
            type: string
  Attributes:
    properties:
      studentID:
        type: string
        description: OSU ID of student attributed to note
      creatorID:
        type: string
        description: OSU ID of person who created the note
      createDate:
        type: string
        format: date-time
      modifierID:
        type: string
        description: OSU ID of person who modified the note 
      modifyDate:
        type: string
        format: date-time
      school:
        type: string
        description: School attributed to note
      degree:
        type: string
        description: Degree attributed to note
      note:
        type: string
        description: Content of note
  Links:
    properties:
      self:
        type: string
      first:
        type: string
      last:
        type: string
      prev:
        type: string
      next:
        type: string
  Error:
    properties:
      status:
        type: integer
        description: HTTP status code.
      developerMessage:
        type: string
        description: An error string aimed at developers.
      userMesage:
        type: string
        description: An error string aimed at end users.
      code:
        type: integer
        description: Error code.
      details:
        type: string
        description: A link to further information about the error.
